version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - postgres:db
    volumes:
      - ./:/var/www/html

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/dbstore
    volumes:
      - dbstore:/var/lib/postgresql/data/dbstore

volumes:
  dbstore:
    external: false
